import numpy as np
a = np.arange(15)
print(a)
a = np.arange(15).reshape(3, 5)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(len(a.shape))
print(a.size)
print(a.dtype)
a = np.arange(15,dtype=np.int16).reshape(3, 5)
print(a)
print(a.dtype)
print(a.dtype.name)
print(a.itemsize)
print(a.dtype.itemsize)
print(a.data)