import numpy as np
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
print(type(b))
print(b.dtype)
print(b.ndim)
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)
print(type(c))
print(c.dtype)
print(c.ndim)
d = np.array([[(1,2),(3,4)],[(5,6),(7,8)]])
print(d)
print(d.ndim)
print(d.dtype)