import numpy as np
rg = np.random.default_rng(1)
print(rg)
a = np.floor(10 * rg.random((3, 4)))
print(a)
print(a.shape)
print(a.ravel())
print(a.reshape(6, 2))
print(a.reshape(3, -1))
print(a.T)
print(a.T.shape)
print(a.shape)
a.resize((2, 6))
print(a)